sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: jp/WhBttK0z20FFaalqFZBAgrzkCDt4nLjrjsAWCzBtvVd+OnefjfmxWWxj6G5mTGerjSMFm1XyN3Vc+Q2hsUQuyJdjSL5pQ8rtC6jQCU7WwxV75B0BT8cK/D2ZgPFIfOFqwV7nLyEv7sb8hj6TXBwWy+lHB+B8Cjhe2AwS4RRvfsfRPPx/rdeemrCno9K25o29TEA43VnxiZSUzgoHOQ8dvsvXMpdluUZjp62A7T9AGcPJIkl9P6Laj/uSVDyg6mWIbGdZd/01g91EfwhuxCCRzeTPzBYIp9detK0kBBUKR0IjT7LZLUhxGT7ZP6gEn/z4U0GjmoVhg+li8nWNkZzShH5g83Rnn1No5fYIcJGoAAFCv8VW0DMXTOowtEctmKMqnGyZZzBKTn+rSWqbY913EKg9ImYoxrBccTeFsuzrJolFJG9P0LxzZVU6G1xAq4eJCESLXcDLgdMF14xBzGiTwdNxzHB6JecdR3M4dTxpEoci1nAF2BG1qFYHfHjc/9rIr5m6Eup3Mu6qtmS3uwdeO1289u/A9v9BsMvd+9GS1FPO4h8p+J4U+OhTrM1m1feK9iw+TU5whtiUtmvYfEd2xfUmailV4vh16BFrCQvekDLwIqu1sWazeAlQG0Mn5TwQqClT5efOZ5M99PZeu5rZGArtXA3Dl/fnG+s/VtX0=
  - secure: dBh2F3UwhtZoCyP9lFc1hmD+5YBaXEynBRZAxGHHsNkdSx011A0gsrYY+fXuL8Xhi9WDHveVoENxB2mWJwn0mV8/H9ZEPGQAnikbtAQtoEkbm3/2bQ1yCYqi2zVgyyidFjJZ7PTYN4NQ0gsPhTjWD5YJDcocMgRjxWSVr6JeODpC6ct8V/eQwURRCbUXTkqDj57b/dLXyFC+wt8Ov3UA0KGj4DHEQSukFLtV4I335blAebOCEymSxQZv+0BOUCol3LIrzRUiRYtFwyeNfBo1xyXsnpipPSTCnguqUGjUkAu5gbVHFfOL+ue7UkAiBFZhr02UM7XNvaS16aXqxqQ3lVWNMuOkzmD7fzIDgZ0ThGMaFZFirCO4wVP+6CBTtPMn/1eCVLuTFnH/3lF3YVInQ103U4cjUyZ9Rkoxs7uoT53kp7MsT+dPsCKeCMGAgCTD6+KsoBv+ykTlNr93GTNGtfeSVlSmHwKh56jWZ8dIu5Ov4KVjJRHjkC0+IUisXiNPZLTjaBGzktyzHqTDgn9uU4eu3IbJF/aN6K5Z6ZwvpWHs2vbdlg7cId5QI0GD9gzZZAhdoAQxs8rsbNlXCeYviVSnYYzljbidhtyONA8JX9GCu1LSqPNrfRQYM0pEMSeGQqWQOTs11mVJ+2YYEF7wzKdPMilpplH9eHr/htSg7LY=
