server:
  applicationConnectors:
  - type: http
    port: 9008
  adminConnectors:
  - type: http
    port: 9108
logging:
  level: INFO
  loggers:
    org.metadatacenter: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: ${CEDAR_HOME}/log/cedar-folder-server.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ${CEDAR_HOME}/log/cedar-folder-server-%d.log
      archivedFileCount: 5
      timeZone: UTC
